## Решение

In [9]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
  
#Вариант 13

data = [[4,3,2,2],
        [1,4,5,8]]

new_x1 = data[0][0] - data[1][0]
f1 = [new_x1, data[1][0]]
x1 = [0,1]
y1 = [data[1][0], new_x1 + data[1][0]]
print(f'B1: {new_x1}p1 + {data[1][0]}')

new_x2 = data[0][1] - data[1][1]
f2 = [new_x2, data[1][1]]
x2 = [0,1]
y2 = [data[1][1], new_x2 + data[1][1]]
print(f'B2: {new_x2}p1 + {data[1][1]}')

new_x3 = data[0][2] - data[1][2]
f3 = [new_x3, data[1][2]]
x3 = [0,1]
y3 = [data[1][2], new_x3 + data[1][2]]
print(f'B3: {new_x3}p1 + {data[1][2]}')

new_x4 = data[0][3] - data[1][3]
f4 = [new_x4, data[1][3]]
x4 = [0,1]
y4 = [data[1][3], new_x4 + data[1][3]]
print(f'B4: {new_x4}p1 + {data[1][3]}')

x_N = (data[1][2] - data[1][0]) / (new_x1 - new_x3)
y_N = new_x1 * x_N + data[1][0]
print(f'N = [{x_N},{y_N}]')

print(f'f(1,q*) = {data[0][0] - data[0][2]}q1* + {data[0][2]}')
print(f'f(3,q*) = {data[1][0] - data[1][2]}q1* + {data[0][2]}')
q1 = (data[1][2] - data[0][2]) / ((data[0][0] - data[0][2]) - (data[1][0] - data[1][2]))
q2 = 1 - q1
print(f'q1* = {q1}\n'
      f'q2* = {q2}')

print('\nОтвет:\n'
      f'p* = [{x_N},{1 - x_N}]\n'
      f'q* = [{q1}, 0, {q2}, 0]\n'
      f'v = {y_N}')

plt.plot(x1, y1, color='green')
plt.plot(x2, y2, color='blue')
plt.plot(x3, y3, color='red')
plt.plot(x4, y4, color='orange')
plt.scatter(x_N, y_N, color='black', marker='o')
plt.text(0,1.3, 'B1', fontsize=14, color='green')
plt.text(0,3.5, 'B2', fontsize=14, color='blue')
plt.text(0,5.3, 'B3', fontsize=14, color='red')
plt.text(0,7.3, 'B4', fontsize=14, color='orange')
plt.text(0.65,2.3, 'N', fontsize=14, color='black')
plt.grid(True)
plt.show()


B1: 3p1 + 1
B2: -1p1 + 4
B3: -3p1 + 5
B4: -6p1 + 8
N = [0.6666666666666666,3.0]
f(1,q*) = 2q1* + 2
f(3,q*) = -4q1* + 2
q1* = 0.5
q2* = 0.5

Ответ:
p* = [0.6666666666666666,0.33333333333333337]
q* = [0.5, 0, 0.5, 0]
v = 3.0


### Имитационная модель

In [10]:
N = int(input('Введите количество раундов: '))

Введите количество раундов: 10000


In [11]:
import numpy as np
from prettytable import PrettyTable

probabilities_p = [2/3, 1/3]
random_p = np.random.choice([1, 2], size=N, p=probabilities_p)

# Вывод первых 10 элементов массива 
print(random_p[:10])


[1 2 2 1 1 1 1 1 2 1]


In [13]:
probabilities_q = [1/2, 0, 1/2, 0]
random_q = np.random.choice([1, 2, 3, 4], size=N, p=probabilities_q)

# Вывод первых 10 элементов массива 
print(random_q[:10])

[1 3 3 3 1 3 1 1 3 3]


In [12]:
def game_round(p, q, n=0):
    table = PrettyTable()
    table.field_names = ["", "B1", "B2", "B3", "B4"]

    # Добавление данных в таблицу
    A = [[4, 3, 2, 2], [1, 4, 5, 8]]
    table.add_row(["A1"] + A[0])
    table.add_row(["A2"] + A[1])
    
    if n != 0:
        print(table)
        print(f'p = {p}, q = {q}, a = {A[p-1][q-1]}')
    
    return A[p-1][q-1]
                
    

In [14]:
n = int(input('Введите демонстрационный шаг: '))

Введите демонстрационный шаг: 6


In [15]:
result = game_round(random_p[n-1], random_q[n-1], n)

+----+----+----+----+----+
|    | B1 | B2 | B3 | B4 |
+----+----+----+----+----+
| A1 | 4  | 3  | 2  | 2  |
| A2 | 1  | 4  | 5  | 8  |
+----+----+----+----+----+
p = 1, q = 3, a = 2


In [16]:
result = []

for i in range(N):
    p = random_p[i]
    q = random_q[i]
        
    a = game_round(p, q)
    result.append(a)

In [17]:
print(f'Цена игры: {round(sum(result)/N, 2)}')

Цена игры: 3.01


#### Изменим вероятности 

In [18]:
m = int(input('Введите количество варинтов вероятностей: '))

Введите количество варинтов вероятностей: 15


In [19]:
p_variants = np.random.rand(m)

In [20]:
p_variants = np.sort(p_variants)
p_variants

array([0.01930471, 0.10591569, 0.10916904, 0.23320987, 0.2439421 ,
       0.26717492, 0.46659059, 0.56167347, 0.58127208, 0.67240268,
       0.71153475, 0.76456487, 0.85929149, 0.88083881, 0.92046704])

In [21]:
def game(pv, qv):
    random_p1 = np.random.choice([1, 2], size=N, p=pv)
    random_q1 = np.random.choice([1, 2, 3, 4], size=N, p=qv)
                                 
    result = []
    for i in range(N):
        pv = random_p1[i]
        qv = random_q1[i]

        a = game_round(pv, qv)
        result.append(a)
        
    return round(sum(result)/N, 2)
    

In [22]:
for i in range(m):
    pv = [p_variants[i], 1 - p_variants[i]]
    qv = [1/2, 0, 1/2, 0]
    print(f'p = {pv}  Цена игры: {game(pv, qv)}')

    

p = [0.019304707076376215, 0.9806952929236238]  Цена игры: 3.0
p = [0.1059156873927165, 0.8940843126072835]  Цена игры: 3.0
p = [0.10916904348705836, 0.8908309565129416]  Цена игры: 2.99
p = [0.23320987008926541, 0.7667901299107346]  Цена игры: 2.99
p = [0.24394209583927107, 0.7560579041607289]  Цена игры: 3.02
p = [0.2671749218884416, 0.7328250781115584]  Цена игры: 3.01
p = [0.4665905880644188, 0.5334094119355812]  Цена игры: 3.02
p = [0.5616734682385903, 0.4383265317614097]  Цена игры: 2.99
p = [0.5812720783538857, 0.4187279216461143]  Цена игры: 2.98
p = [0.6724026842375667, 0.32759731576243334]  Цена игры: 3.0
p = [0.7115347546793006, 0.2884652453206994]  Цена игры: 2.98
p = [0.7645648665289785, 0.23543513347102152]  Цена игры: 3.0
p = [0.8592914938165155, 0.14070850618348452]  Цена игры: 3.0
p = [0.8808388053257905, 0.11916119467420949]  Цена игры: 3.0
p = [0.9204670438891219, 0.07953295611087807]  Цена игры: 3.0


In [23]:
q_variants = np.random.rand(m)

In [24]:
q_variants = np.sort(q_variants)
q_variants

array([0.02052687, 0.0263429 , 0.09345433, 0.13320073, 0.1609249 ,
       0.17747145, 0.20100748, 0.22926843, 0.32187201, 0.48490105,
       0.57719751, 0.62406379, 0.77293298, 0.89893401, 0.99884706])

In [25]:
for i in range(m):
    pv = [2/3, 1/3]
    qv = [q_variants[i], 0, 1 - q_variants[i], 0]
    print(f'q = {qv} Цена игры: {game(pv, qv)}')


q = [0.02052686674998161, 0, 0.9794731332500184, 0] Цена игры: 2.99
q = [0.026342903119040972, 0, 0.973657096880959, 0] Цена игры: 3.01
q = [0.09345432924696195, 0, 0.906545670753038, 0] Цена игры: 2.98
q = [0.13320072980158482, 0, 0.8667992701984152, 0] Цена игры: 2.99
q = [0.16092489610058147, 0, 0.8390751038994185, 0] Цена игры: 2.99
q = [0.1774714527791016, 0, 0.8225285472208984, 0] Цена игры: 3.02
q = [0.20100747835659916, 0, 0.7989925216434008, 0] Цена игры: 3.0
q = [0.22926843162850796, 0, 0.770731568371492, 0] Цена игры: 3.01
q = [0.32187200871215804, 0, 0.678127991287842, 0] Цена игры: 3.02
q = [0.4849010526729114, 0, 0.5150989473270886, 0] Цена игры: 3.02
q = [0.5771975062337289, 0, 0.4228024937662711, 0] Цена игры: 3.01
q = [0.6240637882071575, 0, 0.37593621179284253, 0] Цена игры: 3.02
q = [0.7729329829475535, 0, 0.22706701705244647, 0] Цена игры: 3.02
q = [0.8989340144655685, 0, 0.10106598553443147, 0] Цена игры: 2.97
q = [0.9988470585951489, 0, 0.0011529414048511155, 0] Ц

In [26]:
q_variants = []

for _ in range(m):
    random_numbers = np.random.rand(4)
    
    # Нормируем массив, чтобы сумма была равна 1
    normalized_numbers = random_numbers / np.sum(random_numbers)
    
    if np.all(normalized_numbers > 0):
        q_variants.append(normalized_numbers)

        
for i in range(m):
    pv = [2/3, 1/3]
    qv = q_variants[i]
    print(f'q = {qv} Цена игры: {game(pv, qv)}')


q = [0.26332301 0.2379518  0.33806146 0.16066373] Цена игры: 3.25
q = [0.53752933 0.21071367 0.01638684 0.23537017] Цена игры: 3.29
q = [0.28621878 0.2945441  0.24174178 0.17749534] Цена игры: 3.27
q = [0.45289189 0.22584693 0.24481747 0.07644371] Цена игры: 3.15
q = [0.20767737 0.45443405 0.12268496 0.21520362] Цена игры: 3.37
q = [0.10067688 0.08259782 0.63054543 0.18617987] Цена игры: 3.19
q = [0.02545298 0.47566282 0.12996272 0.36892148] Цена игры: 3.5
q = [0.33773368 0.25332334 0.23413659 0.17480639] Цена игры: 3.27
q = [0.25748297 0.22630493 0.31597981 0.20023229] Цена игры: 3.28
q = [0.30707739 0.26581987 0.24197831 0.18512444] Цена игры: 3.27
q = [0.45843866 0.14885896 0.03153512 0.36116726] Цена игры: 3.45
q = [0.31784026 0.14049054 0.32276143 0.21890778] Цена игры: 3.28
q = [0.33010223 0.3152108  0.15799061 0.19669636] Цена игры: 3.31
q = [0.24199314 0.0461601  0.31605516 0.3957916 ] Цена игры: 3.44
q = [0.26510555 0.30392109 0.39109704 0.03987633] Цена игры: 3.14


### Вывод:

При играх в рамках активных оптимальных стратегий игроков цена игры меняется не существенно. При выборе иных стратегий цена игры существенно изменяется.